export const mockJobs = [
  {
    id: 1,
    title: 'Senior React Developer',
    department: 'Engineering',
    location: 'Remote',
    salary: '$120k - $150k',
    status: 'Open',
    applicants: 24,
    posted: '2024-12-01',
  },
  {
    id: 2,
    title: 'Product Manager',
    department: 'Product',
    location: 'New York',
    salary: '$100k - $130k',
    status: 'Open',
    applicants: 18,
    posted: '2024-11-28',
  },
  {
    id: 3,
    title: 'UI/UX Designer',
    department: 'Design',
    location: 'San Francisco',
    salary: '$90k - $120k',
    status: 'Open',
    applicants: 32,
    posted: '2024-11-25',
  },
  {
    id: 4,
    title: 'Data Scientist',
    department: 'Data',
    location: 'Remote',
    salary: '$130k - $160k',
    status: 'Closed',
    applicants: 45,
    posted: '2024-10-15',
  },
];

export const mockCandidates = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    position: 'Senior React Developer',
    status: 'Interview Scheduled',
    appliedDate: '2024-12-01',
    rating: 4.5,
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane@example.com',
    position: 'Product Manager',
    status: 'Under Review',
    appliedDate: '2024-11-28',
    rating: 4.0,
  },
  {
    id: 3,
    name: 'Mike Johnson',
    email: 'mike@example.com',
    position: 'UI/UX Designer',
    status: 'Rejected',
    appliedDate: '2024-11-27',
    rating: 2.5,
  },
  {
    id: 4,
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    position: 'Senior React Developer',
    status: 'Offer Extended',
    appliedDate: '2024-11-20',
    rating: 5.0,
  },
];

export const mockInterviews = [
  {
    id: 1,
    candidateName: 'John Doe',
    position: 'Senior React Developer',
    interviewDate: '2024-12-15',
    interviewTime: '10:00 AM',
    interviewer: 'Alice Brown',
    status: 'Scheduled',
    type: 'Technical',
  },
  {
    id: 2,
    candidateName: 'Jane Smith',
    position: 'Product Manager',
    interviewDate: '2024-12-16',
    interviewTime: '02:00 PM',
    interviewer: 'Bob Wilson',
    status: 'Scheduled',
    type: 'HR Round',
  },
  {
    id: 3,
    candidateName: 'Sarah Williams',
    position: 'Senior React Developer',
    interviewDate: '2024-12-10',
    interviewTime: '11:30 AM',
    interviewer: 'Alice Brown',
    status: 'Completed',
    type: 'Final Round',
  },
];

export const mockOffers = [
  {
    id: 1,
    candidateName: 'Sarah Williams',
    position: 'Senior React Developer',
    offerDate: '2024-12-05',
    salary: '$140k',
    status: 'Accepted',
    startDate: '2025-01-15',
  },
  {
    id: 2,
    candidateName: 'Robert Brown',
    position: 'Data Scientist',
    offerDate: '2024-12-03',
    salary: '$150k',
    status: 'Pending',
    startDate: '2025-02-01',
  },
];

export const dashboardStats = [
  {
    title: 'Total Jobs',
    value: 12,
    icon: 'briefcase',
    trend: '+2 this month',
    color: 'blue',
  },
  {
    title: 'Active Candidates',
    value: 156,
    icon: 'users',
    trend: '+24 this week',
    color: 'green',
  },
  {
    title: 'Scheduled Interviews',
    value: 8,
    icon: 'calendar',
    trend: '+3 upcoming',
    color: 'purple',
  },
  {
    title: 'Pending Offers',
    value: 3,
    icon: 'file-text',
    trend: '2 awaiting response',
    color: 'orange',
  },
];
